### ISSUE TITLE
Unrelated Question

### ISSUE THREAD

**Issue by Tgamer500** [felikcat/inflatable-starter-kit#1]
I hate to post an issue here because I know it is off topic but I have found no other way to get in contact with you. 
Do you still have your unlimited tether repository? I found it very useful and was using it as a guide right before you deleted/privated it. If you would be so kind as to send me the repository (Tgamer500@protonmail.com) or re-upload it to your github so I can fork it before you take it down it would be of great benefit to me and many others. Thank you.

**Comment by felikcat** [comment]
https://privatebin.net/?299692b75c97e2b8#FikuQJyd9hVMs7pb8fUMuaNgCSHKKjKXLjZeWMYwks9R
`du5m8eQ7XfvYe8rm5RHu6kN56mRXQzRpncx9PG52LVZLVxcqTdyZjYSLwY`
